# Generated by Django 4.2.28 on 2026-03-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='segment',
            field=models.CharField(choices=[('family', 'Family'), ('work', 'Work'), ('friends', 'Friends'), ('other', 'Other'), ('favourite', 'Favourite')], default='other', max_length=255),
        ),
    ]
