# Generated by Django 4.2.28 on 2026-03-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_birthday_contact_is_blocked_contact_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
